#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and hi on the 9th time
i="1"
while ((i<10))
do 
echo "Best School"
if [ $i -eq 8 ]
then 
echo -e "Best School \n Hi"
fi
((i++))
done
