#!/usr/bin/env bash
#managing file manage_my_process
pidfile="/var/run/my_process.pid"
start (){
sudo systemctl start manage_my_process
echo "$$" > "$pidfile"
echo 'manage_my_process started'
}
stop (){
sudo systemctl stop manage_my_process
rm "$pidfile"
echo 'manage_my_process stopped'
}
restart (){
sudo systemctl stop manage_my_process
rm "$pidfile"
sudo systemctl start manage_my_process
echo "$$" > "$pidfile"
echo 'manage_my_process restarted'
}
case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo 'Usage: manage_my_process {start|stop|restart}'
esac
