#!/usr/bin/env bash
#managing file manage_my_process
start (){
sudo systemctl start manage_my_process
echo "$$" > /var/run/my_process.pid
echo "manage_my_process started"
}
stop (){
sudo systemctl stop manage_my_process
rm -f /var/run/my_process.pid
echo "manage_my_process stopped"
}
restart (){
sudo systemctl stop manage_my_process
rm -f /var/run/my_process.pid
sudo systemctl start manage_my_process
echo "$$" > /var/run/my_process.pid
echo "manage_my_process restarted"
}
if [ "$0" = 'start' ]; then
        start
elif [ "$0" = 'stop' ]; then
        stop
elif [ "$0" = 'restart' ]; then
        restart
else
        echo "Usage: manage_my_process {start|stop|restart}"
fi
