#!/usr/bin/env bash
#print I am invincible!!! when receiving a SIGTERM signal
handle_sigterm() {
  echo "I am invincible!!!"
  exit 0
}
trap 'handle_sigterm' SIGTERM
while :
do 
echo "To infinity and beyond"
done
