#!/usr/bin/env bash
#print I am invincible!!! when receiving a SIGTERM signal
handle_kill() {
  echo "I am invincible!!!"
  exit 0
}
trap 'handle_kill' kill
while :
do 
echo "To infinity and beyond"
done
