#!/usr/bin/env bash
# script that:
#Indefinitely writes I am alive! to the file /tmp/my_process
#In between every I am alive! message, the program should pause for 2 seconds
myprocess="/tmp/my_process"
echo "#!/usr/bin/env bash
while : 
do
echo 'I am alive'
sleep 2
done" > $myprocess

